version: '3.8'

services:
  app:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./conf/:/etc/nginx/conf.d/:ro
    restart: always
